language: node_js
node_js:
  - "0.12"

# By default, Travis runs "npm install" to install dependencies.

# Run the tests & submit code coverage data to Coveralls
script: npm run travis

sudo: false   # use container-based architecture; starts up faster